// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProduct(arg1) {
  return window['go']['main']['App']['AddProduct'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteFurnizor(arg1) {
  return window['go']['main']['App']['DeleteFurnizor'](arg1);
}

export function ExportPDF(arg1) {
  return window['go']['main']['App']['ExportPDF'](arg1);
}

export function GetDocument(arg1) {
  return window['go']['main']['App']['GetDocument'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListDocuments() {
  return window['go']['main']['App']['ListDocuments']();
}

export function ListFurnizori() {
  return window['go']['main']['App']['ListFurnizori']();
}

export function ListProducts() {
  return window['go']['main']['App']['ListProducts']();
}

export function NewDocumentDraft() {
  return window['go']['main']['App']['NewDocumentDraft']();
}

export function SaveDocument(arg1) {
  return window['go']['main']['App']['SaveDocument'](arg1);
}

export function SaveProducts(arg1) {
  return window['go']['main']['App']['SaveProducts'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
